// <auto-generated />
using HierarchicalStructureOfDirectories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HierarchicalStructureOfDirectories.Data.Migrations
{
    [DbContext(typeof(DirectoriesContext))]
    partial class DirectoriesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HierarchicalStructureOfDirectories.Models.FileDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directorys");
                });

            modelBuilder.Entity("HierarchicalStructureOfDirectories.Models.RelationshipBetweenFileDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectoryChildId")
                        .HasColumnType("int");

                    b.Property<int>("DirectoryParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RelationshipBetweenFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
